import {Platform} from 'react-native';
import {fontRef, heightRef} from './screenSize';

export const fontSizes: any = {
  f5: Platform.OS == 'android' ? 6 * fontRef : 5 * fontRef,
  f6: Platform.OS == 'android' ? 7 * fontRef : 6 * fontRef,
  f7: Platform.OS == 'android' ? 8 * fontRef : 7 * fontRef,
  f8: Platform.OS == 'android' ? 9 * fontRef : 8 * fontRef,
  f9: Platform.OS == 'android' ? 10 * fontRef : 9 * fontRef,
  f10: Platform.OS == 'android' ? 11 * fontRef : 10 * fontRef,
  f11: Platform.OS == 'android' ? 12 * fontRef : 11 * fontRef,
  f12: Platform.OS == 'android' ? 13 * fontRef : 12 * fontRef,
  f13: Platform.OS == 'android' ? 14 * fontRef : 13 * fontRef,
  f14: Platform.OS == 'android' ? 15 * fontRef : 14 * fontRef,
  f15: Platform.OS == 'android' ? 16 * fontRef : 15 * fontRef,
  f16: Platform.OS == 'android' ? 17 * fontRef : 16 * fontRef,
  f17: Platform.OS == 'android' ? 18 * fontRef : 17 * fontRef,
  f18: Platform.OS == 'android' ? 19 * fontRef : 18 * fontRef,
  f19: Platform.OS == 'android' ? 20 * fontRef : 19 * fontRef,
  f20: Platform.OS == 'android' ? 21 * fontRef : 20 * fontRef,
  f21: Platform.OS == 'android' ? 22 * fontRef : 21 * fontRef,
  f22: Platform.OS == 'android' ? 23 * fontRef : 22 * fontRef,
  f23: Platform.OS == 'android' ? 24 * fontRef : 23 * fontRef,
  f24: Platform.OS == 'android' ? 25 * fontRef : 24 * fontRef,
  f25: Platform.OS == 'android' ? 26 * fontRef : 25 * fontRef,
  f26: Platform.OS == 'android' ? 27 * fontRef : 26 * fontRef,
  f27: Platform.OS == 'android' ? 28 * fontRef : 27 * fontRef,
  f28: Platform.OS == 'android' ? 29 * fontRef : 28 * fontRef,
  f29: Platform.OS == 'android' ? 30 * fontRef : 29 * fontRef,
  f30: Platform.OS == 'android' ? 31 * fontRef : 30 * fontRef,
  f31: Platform.OS == 'android' ? 32 * fontRef : 31 * fontRef,
  f32: Platform.OS == 'android' ? 33 * fontRef : 32 * fontRef,
  f33: Platform.OS == 'android' ? 34 * fontRef : 33 * fontRef,
  f34: Platform.OS == 'android' ? 35 * fontRef : 34 * fontRef,
  f35: Platform.OS == 'android' ? 36 * fontRef : 35 * fontRef,
  f36: Platform.OS == 'android' ? 37 * fontRef : 36 * fontRef,
  f37: Platform.OS == 'android' ? 38 * fontRef : 37 * fontRef,
  f38: Platform.OS == 'android' ? 39 * fontRef : 38 * fontRef,
  f39: Platform.OS == 'android' ? 40 * fontRef : 39 * fontRef,
  f40: Platform.OS == 'android' ? 41 * fontRef : 40 * fontRef,
};
